swagger: '2.0'
info:
  description: |
    PizzaHouse OrderConfirmationService
  version: 1.0.0
  title: PizzaHouse OrderConfirmationService
  contact:
    email: brianlaihkhk@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

tags:
- name: order
  description: Order Related endpoint


# schemes:
# - http
paths:
  /confirm:
    post:
      tags:
      - order
      summary: Order confirmation
      operationId: submitOrderConfirmation
      consumes:
      - text/plain
      produces:
      - text/plain
      parameters:
      - name: jwtString
        in: query
        description: Jwt encoded string
        required: true
        type: string
      responses:
        200:
          description: Jwt encoded string

      description: Create new user

          

# Added by API Auto Mocking Plugin
basePath: /OrderConfirmationService/
schemes:
 - https
 - http