swagger: '2.0'
info:
  description: |
    PizzaHouse PizzaService
  version: 1.0.0
  title: PizzaHouse PizzaService
  contact:
    email: brianlaihkhk@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

tags:
- name: order
  description: Order Related endpoint
- name: user
  description: User Related endpoint

# schemes:
# - http
paths:
  /create:
    post:
      tags:
      - user
      summary: Create new User
      operationId: addUser
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Login object
        required: true
        schema:
          $ref: '#/definitions/CreateUser'
      responses:
        200:
          $ref: '#/definitions/Response'

      description: Create new user

  /login:
    post:
      tags:
      - user
      description: User login
      operationId: createUser
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Login object
        required: true
        schema:
          $ref: '#/definitions/UserLogin'
      responses:
        200:
          $ref: '#/definitions/Response'
      summary: User login

  /order:
    post:
      tags:
      - order
      description: User order
      operationId: subitOrder
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Order object
        required: true
        schema:
          $ref: '#/definitions/SubmitOrder'
      responses:
        200:
          $ref: '#/definitions/Response'
      summary: User login

definitions:
  Response:
    type: object
    properties:
      isSuccess:
        type: boolean
        format: boolean
      payload:
        type: object
        format: object
      error:
        $ref: '#/definitions/Error'

  CreateUser:
    type: object
    properties:
      username:
        type: string
        format: string
      firstname:
        type: string
        format: string
      lastname:
        type: string
        format: string
      password:
        type: string
        format: string
        

  UserLogin:
    type: object
    properties:
      username:
        type: string
        format: string
      password:
        type: string
        format: string

      
  SubmitOrder:
    type: object
    properties:
      userId:
        type: integer
        format: int
      session:
        type: string
        format: string
      details:
        $ref: '#/definitions/OrderDetail'

  Error:
    type: object
    properties:
      errorCode:
        type: integer
        format: integer
      errorMessage:
        type: string
        format: string

  OrderDetail:
    type: object
    properties:
      pizzaTypeId:
        type: integer
        format: integer
      pizzaSizeId:
        type: integer
        format: integer
      quantity:
        type: integer
        format: integer
      pizzaToppingIdList:
        type: array
        items:
          type: integer
          format: integer
          

# Added by API Auto Mocking Plugin
basePath: /PizzaHouseService/
schemes:
 - https
 - http